USE AdventureWorks2012;
GO 

SELECT COUNT (*) AS [COUNT OF ROWS],
		MAX(TOTALDUE) AS [MAX TOTAL],
		MIN(TOTALDUE) AS [MIN TOTAL],
		SUM(TOTALDUE) AS [SUM TOTAL],
		AVG(TOTALDUE) AS [AVG TOTAL]
FROM SALES.SALESORDERHEADER